// Date: 15.5.2017 17.29.20
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.wildmobsmod.entity.passive.goat;

import org.lwjgl.opengl.GL11;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelGoat extends ModelBase
{
	// fields
	ModelRenderer body;
	ModelRenderer udders;
	ModelRenderer leg1;
	ModelRenderer leg2;
	ModelRenderer leg3;
	ModelRenderer leg4;
	ModelRenderer head;
	ModelRenderer neck;
	ModelRenderer nose;
	ModelRenderer horn1;
	ModelRenderer horn2;

	protected static void convertToChild(ModelRenderer parent, ModelRenderer child)
	{
		// move child rotation point to be relative to parent
		child.rotationPointX -= parent.rotationPointX;
		child.rotationPointY -= parent.rotationPointY;
		child.rotationPointZ -= parent.rotationPointZ;
		// make rotations relative to parent
		child.rotateAngleX -= parent.rotateAngleX;
		child.rotateAngleY -= parent.rotateAngleY;
		child.rotateAngleZ -= parent.rotateAngleZ;
		// create relationship
		parent.addChild(child);
	}

	public ModelGoat()
	{
		textureWidth = 64;
		textureHeight = 32;

		body = new ModelRenderer(this, 10, 10);
		body.addBox(-2.5F, 0F, -4F, 5, 12, 7);
		body.setRotationPoint(0F, 14F, -6F);
		body.setTextureSize(64, 32);
		setRotation(body, 1.570796F, 0F, 0F);
		udders = new ModelRenderer(this, 34, 0);
		udders.addBox(-2F, 0F, -1F, 4, 4, 1);
		udders.setRotationPoint(0F, 18F, -0.5F);
		udders.setTextureSize(64, 32);
		setRotation(udders, 1.570796F, 0F, 0F);
		leg1 = new ModelRenderer(this, 0, 14);
		leg1.addBox(-1F, 0F, -1.5F, 2, 6, 2);
		leg1.setRotationPoint(-1.5F, 18F, 5F);
		leg1.setTextureSize(64, 32);
		setRotation(leg1, 0F, 0F, 0F);
		leg2 = new ModelRenderer(this, 0, 14);
		leg2.addBox(-1F, 0F, -1.5F, 2, 6, 2);
		leg2.setRotationPoint(1.5F, 18F, 5F);
		leg2.setTextureSize(64, 32);
		setRotation(leg2, 0F, 0F, 0F);
		leg3 = new ModelRenderer(this, 0, 14);
		leg3.addBox(-1F, 0F, -1.5F, 2, 6, 2);
		leg3.setRotationPoint(-1.5F, 18F, -3.5F);
		leg3.setTextureSize(64, 32);
		setRotation(leg3, 0F, 0F, 0F);
		leg4 = new ModelRenderer(this, 0, 14);
		leg4.addBox(-1F, 0F, -1.5F, 2, 6, 2);
		leg4.setRotationPoint(1.5F, 18F, -3.5F);
		leg4.setTextureSize(64, 32);
		setRotation(leg4, 0F, 0F, 0F);
		head = new ModelRenderer(this, 0, 0);
		head.addBox(-2F, -5.3F, -7.5F, 4, 4, 4);
		head.setRotationPoint(0F, 14F, -4F);
		head.setTextureSize(64, 32);
		setRotation(head, 0F, 0F, 0F);
		neck = new ModelRenderer(this, 20, 0);
		neck.addBox(-1.5F, -6F, -2F, 3, 6, 4);
		neck.setRotationPoint(0F, 14.2F, -4.5F);
		neck.setTextureSize(64, 32);
		setRotation(neck, 0.8726646F, 0F, 0F);
		convertToChild(head, neck);
		nose = new ModelRenderer(this, 0, 8);
		nose.addBox(-1.5F, -1.5F, -2.5F, 3, 3, 2);
		nose.setRotationPoint(0F, 11.2F, -11F);
		nose.setTextureSize(64, 32);
		setRotation(nose, 0F, 0F, 0F);
		convertToChild(head, nose);
		horn1 = new ModelRenderer(this, 16, 0);
		horn1.addBox(-0.5F, -4F, -1F, 1, 4, 1);
		horn1.setRotationPoint(-1.1F, 9.8F, -8.5F);
		horn1.setTextureSize(64, 32);
		setRotation(horn1, -0.6981317F, -0.0872665F, -0.1919862F);
		convertToChild(head, horn1);
		horn2 = new ModelRenderer(this, 16, 0);
		horn2.addBox(-0.5F, -4F, -1F, 1, 4, 1);
		horn2.setRotationPoint(1.1F, 9.8F, -8.5F);
		horn2.setTextureSize(64, 32);
		setRotation(horn2, -0.6981317F, 0.0872665F, 0.1919862F);
		convertToChild(head, horn2);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		if(this.isChild)
		{
			float f6 = 2.0F;
			GL11.glPushMatrix();
			GL11.glScalef(1.0F / f6, 1.0F / f6, 1.0F / f6);
			GL11.glTranslatef(0.0F, 24.0F * f5, 0.0F);
			body.render(f5);
			udders.render(f5);
			leg1.render(f5);
			leg2.render(f5);
			leg3.render(f5);
			leg4.render(f5);
			GL11.glPopMatrix();
			GL11.glPushMatrix();
			GL11.glScalef(1.3F / f6, 1.3F / f6, 1.3F / f6);
			GL11.glTranslatef(0.0F, 15.0F * f5, 2.0F * f5);
			head.render(f5);
			GL11.glPopMatrix();
		}
		else
		{
			body.render(f5);
			udders.render(f5);
			leg1.render(f5);
			leg2.render(f5);
			leg3.render(f5);
			leg4.render(f5);
			head.render(f5);
		}
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		this.head.rotateAngleX = f4 / (180F / (float) Math.PI);
		this.head.rotateAngleY = f3 / (360F / (float) Math.PI);
		this.head.rotateAngleX += 0.1F;
		this.leg1.rotateAngleX = MathHelper.cos(f * 0.6662F) * 2.0F * f1;
		this.leg2.rotateAngleX = MathHelper.cos(f * 0.6662F + (float) Math.PI) * 2.0F * f1;
		this.leg3.rotateAngleX = MathHelper.cos(f * 0.6662F + (float) Math.PI) * 2.0F * f1;
		this.leg4.rotateAngleX = MathHelper.cos(f * 0.6662F) * 2.0F * f1;
	}

}
